pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Echo from build"
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo "Echo from test"
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Echo from deliver"
                sh './jenkins/scripts/deliver.sh'
                echo "Echo from deliver after"
            }
        }
    }
}
